chcek the missing value,
fill missing value,
transform into categorial data to numerical,
target column = has_covid divided data and perform train test split

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('/content/covid_toy - covid_toy.csv')

In [ ]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
df.tail()

    age  gender  fever   cough       city has_covid
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

In [ ]:
df.sample()

    age  gender  fever cough     city has_covid
39   50  Female  103.0  Mild  Kolkata        No

In [ ]:
df.columns

Index(['age', 'gender', 'fever', 'cough', 'city', 'has_covid'], dtype='object')

In [ ]:
df.groupby('gender')['has_covid'].value_counts()

gender  has_covid
Female  No           34
        Yes          25
Male    No           21
        Yes          20
Name: count, dtype: int64

In [ ]:
df.groupby('city')['has_covid'].value_counts()

city       has_covid
Bangalore  No           17
           Yes          13
Delhi      No           13
           Yes           9
Kolkata    No           17
           Yes          15
Mumbai     No            8
           Yes           8
Name: count, dtype: int64

In [ ]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
df['fever']=df['fever'].fillna(df['fever'].mean())

In [ ]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
df['gender']=df['gender'].map({'Male':0, 'Female':1})

In [ ]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [ ]:
df['cough']=df['cough'].map({'Mild':0, 'Strong':1})

In [ ]:
df['city']=df['city'].map({'Kolkata':0, 'Bangalore':1, 'Delhi':2, 'Mumbai':3 })

In [ ]:
df['has_covid']=df['has_covid'].map({'Yes':1, 'No':0})

In [ ]:
df.head()

   age  gender  fever  cough  city  has_covid
0   60       0  103.0      0     0          0
1   27       0  100.0      0     2          1
2   42       0  101.0      0     2          0
3   31       1   98.0      0     0          0
4   65       1  101.0      0     3          0

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x=df.drop(columns=['has_covid'])

In [ ]:
y=df['has_covid']

In [ ]:
x_train, x_test,y_train , y_test = train_test_split(x,
                                                    y,
                                                    test_size = 0.2,
                                                    random_state = 52)

In [ ]:
print("Total shape of df :", df.shape)
print('-------------------------------')
print("independent data shape :", x.shape)
print("x_train data shape :", x_train.shape)
print("x_test data shape :",x_test.shape)
print("--------------------------------")
print("Target data shape :", y.shape)
print("y_train data shape :",y_train.shape)
print("y_test data shape :",y_test.shape)

Total shape of df : (100, 6)
-------------------------------
independent data shape : (100, 5)
x_train data shape : (80, 5)
x_test data shape : (20, 5)
--------------------------------
Target data shape : (100,)
y_train data shape : (80,)
y_test data shape : (20,)

**   STDANDARD_SCALAR**

StandardScaler is used to standardize numerical data so that all features are on the same scale.

In [ ]:
# for converting our data into normal distribution we will use standardscaler

In [ ]:
from sklearn.preprocessing import StandardScaler
# StandardScaler rescales numbers so all features are on the same scale,
# without changing their distribution shape(data).
# Ensures all features are on the same scale

In [ ]:
sc = StandardScaler()

In [ ]:
x_train_sc = sc.fit_transform(x_train)    ## fit--> perform operatoin mean , standard deviation
                                          ## transform --> apply the formula to all data

In [ ]:
x_train_new = pd.DataFrame(x_train_sc, columns = x_train.columns)  #convert into dataframe for use numpy round function

In [ ]:
np.round(x_train_new.describe(), 2)

         age  gender  fever  cough   city
count  80.00   80.00  80.00  80.00  80.00
mean    0.00    0.00  -0.00   0.00   0.00
std     1.01    1.01   1.01   1.01   1.01
min    -1.51   -1.29  -1.53  -0.75  -1.19
25%    -0.94   -1.29  -0.61  -0.75  -1.19
50%    -0.03    0.77   0.04  -0.75  -0.26
75%     0.98    0.77   0.56   1.33   0.68
max     1.55    0.77   1.61   1.33   1.61

TIP DATA

In [ ]:
# perform standardscaler to tips data and mean will be zero

In [ ]:
 sns.get_dataset_names() ## to load all dataset

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [ ]:
import seaborn as sns

In [ ]:
df = sns.load_dataset('tips')

In [ ]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [ ]:
df['sex']=df['sex'].map({'Male':0, 'Female':1})
df['smoker']=df['smoker'].map({'Yes':0, 'No':1})
df['day']=df['day'].map({'Sat':0, 'Sun':1, 'Thur':2, 'Fri':3})
df['time']=df['time'].map({'Dinner':0, 'Lunch':1 })

In [ ]:
df.head()

   total_bill   tip sex smoker day time  size
0       16.99  1.01   1      1   1    0     2
1       10.34  1.66   0      1   1    0     3
2       21.01  3.50   0      1   1    0     3
3       23.68  3.31   0      1   1    0     2
4       24.59  3.61   1      1   1    0     4

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x=df.drop(columns=['tip'])

In [ ]:
y=df['tip']

In [ ]:
x_train, x_test, y_train, y_test = train_test_split (x,y, test_size=0.2, random_state=56)

In [ ]:
print("Total shape of df :", df.shape)
print('-------------------------------')
print("independent data shape :", x.shape)
print("x_train data shape :", x_train.shape)
print("x_test data shape :",x_test.shape)
print("--------------------------------")
print("Target data shape :", y.shape)
print("y_train data shape :",y_train.shape)
print("y_test data shape :",y_test.shape)

Total shape of df : (244, 7)
-------------------------------
independent data shape : (244, 6)
x_train data shape : (195, 6)
x_test data shape : (49, 6)
--------------------------------
Target data shape : (244,)
y_train data shape : (195,)
y_test data shape : (49,)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
a = StandardScaler()

In [ ]:
x_train_a = a.fit_transform(x_train)

In [ ]:
x_train_b = pd.DataFrame(x_train_a, columns = x_train.columns)

In [ ]:
np.round(x_train_b.describe(),2)

       total_bill     sex  smoker     day    time    size
count      195.00  195.00  195.00  195.00  195.00  195.00
mean         0.00    0.00   -0.00    0.00    0.00   -0.00
std          1.00    1.00    1.00    1.00    1.00    1.00
min         -1.88   -0.76   -1.26   -1.05   -0.60   -1.69
25%         -0.73   -0.76   -1.26   -1.05   -0.60   -0.61
50%         -0.23   -0.76    0.79   -0.03   -0.60   -0.61
75%          0.47    1.32    0.79    1.00    1.66    0.47
max          3.45    1.32    0.79    2.03    1.66    3.70

In [ ]:
df=sns.load_dataset('iris')

In [ ]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [ ]:
df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [ ]:
df['species']=df['species'].map({'setosa':0, 'versicolor':1, 'virginica':2})

In [ ]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x=df.drop(columns=['species'])

In [ ]:
y=df['species']

In [ ]:
x_train, x_test, y_train, y_test= train_test_split( x, y, test_size=0.2, random_state=98)

In [ ]:
print("Total shape of df :", df.shape)
print('-------------------------------')
print("independent data shape :", x.shape)
print("x_train data shape :", x_train.shape)
print("x_test data shape :",x_test.shape)
print("--------------------------------")
print("Target data shape :", y.shape)
print("y_train data shape :",y_train.shape)
print("y_test data shape :",y_test.shape)

Total shape of df : (150, 5)
-------------------------------
independent data shape : (150, 4)
x_train data shape : (120, 4)
x_test data shape : (30, 4)
--------------------------------
Target data shape : (150,)
y_train data shape : (120,)
y_test data shape : (30,)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
a = StandardScaler

In [ ]:
b = a.fit_transform(x_train)

TypeError: TransformerMixin.fit_transform() missing 1 required positional argument: 'X'

In [ ]:
dataframe = pd.DataFrame(b, columns = x_train.columns)

In [ ]:
np.round(dataframe.describe(), 2)

       sepal_length  sepal_width  petal_length  petal_width
count         16.00        16.00         16.00        16.00
mean          -0.00        -0.00          0.00         0.00
std            1.03         1.03          1.03         1.03
min           -1.63        -1.66         -1.81        -1.67
25%           -0.86        -0.78         -0.65        -0.60
50%            0.08         0.09         -0.07        -0.07
75%            0.86         0.85          1.09         0.47
max            1.47         1.35          1.66         1.54

In [ ]:
df = sns.load_dataset('anagrams')

In [ ]:
df.head()

   subidr    attnr  num1  num2  num3
0       1  divided     2   4.0     7
1       2  divided     3   4.0     5
2       3  divided     3   5.0     6
3       4  divided     5   7.0     5
4       5  divided     4   5.0     8

In [ ]:
df['attnr'].value_counts()

attnr
divided    10
focused    10
Name: count, dtype: int64

In [ ]:
df['attnr']=df['attnr'].map({'divided':0, 'focused':1})

In [ ]:
df.head()

   subidr  attnr  num1  num2  num3
0       1      0     2   4.0     7
1       2      0     3   4.0     5
2       3      0     3   5.0     6
3       4      0     5   7.0     5
4       5      0     4   5.0     8

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x=df.drop(columns=['attnr'])

In [ ]:
y=df['attnr']

In [ ]:
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.2, random_state=89)

In [ ]:
print("Total shape of df :", df.shape)
print('-------------------------------')
print("independent data shape :", x.shape)
print("x_train data shape :", x_train.shape)
print("x_test data shape :",x_test.shape)
print("--------------------------------")
print("Target data shape :", y.shape)
print("y_train data shape :",y_train.shape)
print("y_test data shape :",y_test.shape)

Total shape of df : (20, 5)
-------------------------------
independent data shape : (20, 4)
x_train data shape : (16, 4)
x_test data shape : (4, 4)
--------------------------------
Target data shape : (20,)
y_train data shape : (16,)
y_test data shape : (4,)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
a = StandardScaler()

In [ ]:
b = a.fit_transform(x_train)

In [ ]:
data = pd.DataFrame(b, columns = x_train.columns)

In [ ]:
np.round(data.describe(), 2)

       subidr   num1   num2   num3
count   16.00  16.00  16.00  16.00
mean    -0.00  -0.00   0.00   0.00
std      1.03   1.03   1.03   1.03
min     -1.63  -1.66  -1.81  -1.67
25%     -0.86  -0.78  -0.65  -0.60
50%      0.08   0.09  -0.07  -0.07
75%      0.86   0.85   1.09   0.47
max      1.47   1.35   1.66   1.54

In [ ]:
df_cat = df.select_dtypes(include= "category").columns.to_list()

In [ ]:
### to convert all categorial data into numerical by the help of for loop
for i in df_cat:
  uni = df[i].unique().to_list()
  num = 0
  empty = {}
  for j in uni :
    empty[j] = num
    num +=1
  df[i]=df[i].map(empty)

In [ ]:
df = pd.read_csv('/content/Churn_Modelling - Churn_Modelling.csv')

In [ ]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
df.drop(columns  = ['Geography', 'Surname'], inplace=True )

In [ ]:
df['Gender']=df['Gender'].map({'Female':0, 'Male':1})

In [ ]:
df.head()

,RowNumber,CustomerId,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,0,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,0,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,0,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,0,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,0,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x=df.drop(columns=['Exited'])
y=df['Exited']

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=76)

In [ ]:
print("Total shape of df :", df.shape)
print('-------------------------------')
print("independent data shape :", x.shape)
print("x_train data shape :", x_train.shape)
print("x_test data shape :",x_test.shape)
print("--------------------------------")
print("Target data shape :", y.shape)
print("y_train data shape :",y_train.shape)
print("y_test data shape :",y_test.shape)

Total shape of df : (10000, 12)
-------------------------------
independent data shape : (10000, 11)
x_train data shape : (8000, 11)
x_test data shape : (2000, 11)
--------------------------------
Target data shape : (10000,)
y_train data shape : (8000,)
y_test data shape : (2000,)

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
mn = MinMaxScaler()

In [ ]:
x_train_mn = mn.fit_transform(x_train)

In [ ]:
x_train_new = pd.DataFrame( x_train_mn, columns= x_train.columns)

In [ ]:
np.round(x_train_new.describe(),2)

,RowNumber,CustomerId,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
count,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00
mean,0.50,0.50,0.60,0.54,0.28,0.50,0.30,0.18,0.71,0.51,0.50
std,0.29,0.29,0.19,0.50,0.14,0.29,0.25,0.19,0.46,0.50,0.29
min,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,0.25,0.25,0.47,0.00,0.19,0.20,0.00,0.00,0.00,0.00,0.25
50%,0.50,0.50,0.60,1.00,0.26,0.50,0.39,0.00,1.00,1.00,0.50
75%,0.75,0.75,0.74,1.00,0.35,0.70,0.51,0.33,1.00,1.00,0.75
max,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00

In [ ]:
df = pd.read_csv("/content/Attrition - Attrition.csv")

In [ ]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [ ]:
df.drop(columns=['Department'], inplace=True)

In [ ]:
# df.isnull().sum()

In [ ]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,1,2,Life Sciences,1,1,2,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,8,1,Life Sciences,1,2,3,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,2,2,Other,1,4,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,3,4,Life Sciences,1,5,4,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,2,1,Medical,1,7,1,...,4,80,1,6,3,3,2,2,2,2

In [ ]:
df['Attrition']=df['Attrition'].map({'Yes':0, 'No':1})
df['BusinessTravel']=df['BusinessTravel'].map({'Travel_Rarely':0, 'Travel_Frequently':1, 'Non-Travel':2})
df['EducationField']=df['EducationField'].map({'Life Sciences':0, 'Medical':1, 'Marketing':2, 'Technical Degree':3, 'Other':4, 'Human Resources':5 })

In [ ]:
x=df.drop(columns=['Attrition'])
y=df['Attrition']

In [ ]:
print("Total shape of df :", df.shape)
print('-------------------------------')
print("independent data shape :", x.shape)
print("x_train data shape :", x_train.shape)
print("x_test data shape :",x_test.shape)
print("--------------------------------")
print("Target data shape :", y.shape)
print("y_train data shape :",y_train.shape)
print("y_test data shape :",y_test.shape)

Total shape of df : (1470, 34)
-------------------------------
independent data shape : (1470, 33)
x_train data shape : (8000, 11)
x_test data shape : (2000, 11)
--------------------------------
Target data shape : (1470,)
y_train data shape : (8000,)
y_test data shape : (2000,)

In [ ]:
a= MinMaxScaler()

In [ ]:
b = a.fit_transform(x_train)

In [ ]:
dataframe = pd.DataFrame(b, columns= x_train.columns)

In [ ]:
np.round(dataframe.describe(),2)

,RowNumber,CustomerId,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
count,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00
mean,0.50,0.50,0.60,0.54,0.28,0.50,0.30,0.18,0.71,0.51,0.50
std,0.29,0.29,0.19,0.50,0.14,0.29,0.25,0.19,0.46,0.50,0.29
min,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,0.25,0.25,0.47,0.00,0.19,0.20,0.00,0.00,0.00,0.00,0.25
50%,0.50,0.50,0.60,1.00,0.26,0.50,0.39,0.00,1.00,1.00,0.50
75%,0.75,0.75,0.74,1.00,0.35,0.70,0.51,0.33,1.00,1.00,0.75
max,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00

In [ ]:
df = pd.read_csv